
namespace: codehorn

codehorn:

  configs:
    compiler:
      name: compiler-config
    serviceDiscovery:
      name: service-discovery-config

  pvc:
    name: codehorn-pvc
    storage: 100Gi
    storageClass: standard-rwx

  compilers:
#    c:
#      name: c-compiler
#      compilerImage: "gcc:9.5.0"
#      replicas: 1
#      inputBasePath: c
#    cpp:
#      name: cpp-compiler
#      compilerImage: "gcc:9.5.0"
#      replicas: 1
#      inputBasePath: cpp
    java:
      name: java-compiler
      compilerImage: "amazoncorretto:21"
      replicas: 1
      inputBasePath: java
#    python:
#      name: python-compiler
#      compilerImage: "gcc:9.5.0"
#      replicas: 1
#      inputBasePath: python
#    javascript:
#      name: javascript-compiler
#      compilerImage: "node:21"
#      replicas: 1
#      inputBasePath: javascript

  compilerServices:
#    cExecution:
#      name: c-execution-service
#      image: irsathkareem/codehorn:1.0-c-execution
#      replicas: 1
#      inputBasePath: c
#      daemon: c-compiler
#    cppExecution:
#      name: cpp-execution-service
#      image: irsathkareem/codehorn:1.0-cpp-execution
#      replicas: 1
#      inputBasePath: cpp
#      daemon: cpp-compiler
    javaExecution:
      name: java-execution-service
      image: irsathkareem/codehorn:1.0-java-execution
      replicas: 1
      inputBasePath: java
      daemon: java-compiler
#    pythonExecution:
#      name: python-execution-service
#      image: irsathkareem/codehorn:1.0-python-execution
#      replicas: 1
#      inputBasePath: python
#      daemon: python-compiler
#    javascriptExecution:
#      name: javascript-execution-service
#      image: irsathkareem/codehorn:1.0-javascript-execution
#      replicas: 1
#      inputBasePath: javascript
#      daemon: javascript-compiler

  services:
#    gateway:
#      name: gateway-service
#      image: irsathkareem/codehorn:1.0-gateway
#      replicas: 1
#    problems:
#      name: problems-service
#      image: irsathkareem/codehorn:1.0-problems
#      replicas: 1
#    evaluation:
#      name: evaluation-service
#      image: irsathkareem/codehorn:1.0-evaluation
#      replicas: 1
#    practice:
#      name: practice-service
#      image: irsathkareem/codehorn:1.0-practice
#      replicas: 1
#    dailyChallenge:
#      name: daily-challenge-service
#      image: irsathkareem/codehorn:1.0-daily-challenge
#      replicas: 1
#    contests:
#      name: contests-service
#      image: irsathkareem/codehorn:1.0-contests
#      replicas: 1

  helpers:
    dockerDaemon:
      image: docker:dind
      volumeMountBasePath: /codehorn/executions