
namespace: codehorn

codehorn:

  configs:
    compiler:
      name: compiler-config
    serviceDiscovery:
      name: service-discovery-config

  pvc:
    name: codehorn-pvc
    storage: 100Gi
    storageClass: standard-rwx

  compilers:
    c:
      compilerImage: "gcc:9.5.0"
    cpp:
      compilerImage: "gcc:9.5.0"
    java:
      compilerImage: "amazoncorretto:21"
    python:
      compilerImage: "gcc:9.5.0"
    javascript:
      compilerImage: "node:21"

  compilerServices:
    cExecution:
      name: c-execution-service
      image: irsathkareem/codehorn:1.0-c-execution-service
      replicas: 1
      inputBasePath: /codehorn/executions/c
    cppExecution:
      name: cpp-execution-service
      image: irsathkareem/codehorn:1.0-cpp-execution-service
      replicas: 1
      inputBasePath: /codehorn/executions/cpp
    javaExecution:
      name: java-execution-service
      image: irsathkareem/codehorn:1.0-java-execution-service
      replicas: 1
      inputBasePath: /codehorn/executions/java
    pythonExecution:
      name: python-execution-service
      image: irsathkareem/codehorn:1.0-python-execution-service
      replicas: 1
      inputBasePath: /codehorn/executions/python
    javascriptExecution:
      name: javascript-execution-service
      image: irsathkareem/codehorn:1.0-javascript-execution-service
      replicas: 1
      inputBasePath: /codehorn/executions/javascript

  services:
    gateway:
      name: gateway-service
      image: irsathkareem/codehorn:1.0-gateway-service
      replicas: 1
    problems:
      name: problems-service
      image: irsathkareem/codehorn:1.0-problems-service
      replicas: 1
    evaluation:
      name: evaluation-service
      image: irsathkareem/codehorn:1.0-evaluation-service
      replicas: 1
    practice:
      name: practice-service
      image: irsathkareem/codehorn:1.0-practice-service
      replicas: 1
    dailyChallenge:
      name: daily-challenge-service
      image: irsathkareem/codehorn:1.0-daily-challenge-service
      replicas: 1
    contests:
      name: contests-service
      image: irsathkareem/codehorn:1.0-contests-service
      replicas: 1

  helpers:
    dockerDaemon:
      name: docker-daemon
      image: docker:dind
      replicas: 1
      volumeMountBasePath: /codehorn/executions