services:
  docker-daemon:
    container_name: docker-daemon
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    command:
      - dockerd
      - --host=tcp://0.0.0.0:2375
    healthcheck:
      test: ["CMD-SHELL", "docker -H tcp://localhost:2375 info"]
      interval: 2s
      timeout: 2s
      retries: 30